name: lolnero_node
description: A lolnode mobile node

version: 0.9.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  logging: ^1.0.0
  path_provider: ^2.0.1
  share: ^2.0.1
  shared_preferences: ^2.0.5
  async: ^2.5.0
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/lolnode_icon.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: VT323
      fonts:
        - asset: fonts/VT323/VT323-Regular.ttf
